version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  allow:
  - dependency-name: "github.com/opencontainers/runtime-spec"
    dependency-type: direct

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
      interval: "daily"
  open-pull-requests-limit: 10
