version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - versions: ["*-rc.*"]

- package-ecosystem: gomod
  directory: "test/tools"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - versions: ["*-rc.*"]

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
      interval: "daily"
  open-pull-requests-limit: 10
