version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  labels:
    - "release-note-none"
  open-pull-requests-limit: 10

- package-ecosystem: gomod
  directory: "test/tools"
  schedule:
    interval: weekly
  labels:
    - "release-note-none"
  open-pull-requests-limit: 10

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
      interval: "daily"
  labels:
    - "release-note-none"
  open-pull-requests-limit: 10
